[DROOLS-5910] Enable range index for JoinNode
kiegroup/droolsjbpm-knowledge pull request #498
Opened 2021-01-25 08:37 UTC by tkobayas

- Adding BetaRangeIndexOption

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-5910

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

2021-01-26 10:01 UTC, lucamolteni approved these changes

2021-01-26 13:38 UTC, mariofusco approved these changes

2021-01-26 13:39 UTC, hellowdan approved these changes

2021-01-26 13:47 UTC, mariofusco requested changes
I believe you should also change the kmodule.xsd file to allow the marshalling of the new option as for example I did here https://github.com/kiegroup/droolsjbpm-knowledge/commit/368d55e53d5e4138bb38309bcf2895d89173cb18#diff-9de282dbc1b8dd6fc1911b7056f07588e543bfa697e4415fc4dcc2c0e0f18eddR66

2021-01-27 03:03 UTC, tkobayas commented
> I believe you should also change the kmodule.xsd file to allow the marshalling of the new option as for example I did here [368d55e#diff-9de282dbc1b8dd6fc1911b7056f07588e543bfa697e4415fc4dcc2c0e0f18eddR66](https://github.com/kiegroup/droolsjbpm-knowledge/commit/368d55e53d5e4138bb38309bcf2895d89173cb18#diff-9de282dbc1b8dd6fc1911b7056f07588e543bfa697e4415fc4dcc2c0e0f18eddR66)

Thank you very much for the notice, now added.

2021-01-28 10:02 UTC, mariofusco approved these changes

2021-01-28 10:13 UTC, merged