[JBPM-9882] Adding actual owner to TaskEvent
kiegroup/droolsjbpm-knowledge pull request #548
Opened 2021-09-13 18:34 UTC by fjtirado

With this addition, code retrieving the event can determine which
was the actual owner after the operation was applied.

**JIRA**: 

[link](https://issues.redhat.com/browse/JBPM-9882)

**referenced Pull Requests**: 
https://github.com/kiegroup/jbpm/pull/2017

2021-09-16 10:29 UTC, elguardian requested changes
those methods should not be reflected in there.

2021-09-22 10:51 UTC, elguardian commented on kie-api/src/main/java/org/kie/api/runtime/process/ProcessWorkItemHandlerException.java
> +    private final String processId;
why this files is changed ?

2021-09-22 13:08 UTC, fjtirado commented on kie-api/src/main/java/org/kie/api/runtime/process/ProcessWorkItemHandlerException.java
> +    private final String processId;
Wrong PR, reverting

2021-09-23 07:33 UTC, elguardian approved these changes

2021-09-28 20:51 UTC, afalhambra commented
closing this pr - opening the same on https://github.com/kiegroup/droolsjbpm-knowledge/pull/554

2021-09-28 20:51 UTC, closed without merging