JBPM-9992 Created ExecutionErrorInfoDeleteBuilder
kiegroup/droolsjbpm-knowledge pull request #588
Opened 2022-02-04 12:04 UTC by hbelmiro

Created ExecutionErrorInfoDeleteBuilder.
https://github.com/kiegroup/jbpm/pull/2086 depends on this PR.

JIRA: https://issues.redhat.com/browse/JBPM-9992

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

2022-02-11 08:53 UTC, gmunozfe requested changes

2022-02-11 08:53 UTC, gmunozfe commented on kie-internal/src/main/java/org/kie/internal/query/QueryParameterIdentifiers.java
> +    String ERROR_DATE_LIST = String.valueOf(idGen.getAndIncrement());
Add "public static final"
```suggestion
    public static final String ERROR_DATE_LIST = String.valueOf(idGen.getAndIncrement());
```

2022-02-11 08:53 UTC, gmunozfe commented on kie-internal/src/main/java/org/kie/internal/runtime/manager/audit/query/ExecutionErrorInfoDeleteBuilder.java
> +public interface ExecutionErrorInfoDeleteBuilder extends AuditDateDeleteBuilder<ExecutionErrorInfoDeleteBuilder> {
Please add a javadoc comment with the purpose of the interface

2022-02-11 19:11 UTC, fjtirado approved these changes

2022-02-14 07:45 UTC, elguardian approved these changes

2022-02-14 07:47 UTC, elguardian commented
@hbelmiro I cannot merge till you rebase.

2022-02-14 18:11 UTC, hbelmiro commented
@elguardian rebased

2022-02-15 07:52 UTC, merged